#!/bin/sh
bin="/usr/local/bin/"
bash_completion="/etc/bash_completion.d/"
zsh_completion="/usr/share/zsh/functions/Completion/Unix/"

cp cookman $bin

mkdir -p $bash_completion
cp completion/bash/cookman $bash_completion

mkdir -p $zsh_completion
cp completion/zsh/_cookman $zsh_completion
