#!/bin/sh
bin="/usr/local/bin/"
bash_completion="/etc/bash_completion.d/"
zsh_completion="/usr/share/zsh/functions/Completion/Unix/"

cp woman $bin

mkdir -p $bash_completion
cp completion/bash/woman $bash_completion

mkdir -p $zsh_completion
cp completion/zsh/_woman $zsh_completion
