#!/bin/sh

if [ $# -ne 0 -a "$1" = "--tags" ] ; then
    curl -s "https://based.cooking/" | sed 's/, /\n/g' | grep --line-buffered -Po '(?<=a href\=\"@)[a-z0-9\-]+(?=\.html)' | sort | uniq
    exit 0
fi

if [ $# -ne 0 -a "$1" = "--list" ] ; then
    tag=""
    if [ $# -ne 1 ] ; then
      tag="$(echo @$2 | awk '{print tolower($0)}')"
    fi
    curl -s "https://based.cooking/$tag" | grep --line-buffered -Po '(?<=a href\=\")[a-z0-9\-]+(?=\.html)' | sed 's/-/ /g' | sed 's/\b./\u&/g' | sort | uniq
    exit 0
fi

if ! type "pandoc" > /dev/null; then
  echo "Install pandoc first."
  exit 1
fi

use_pager=true
if [ $# -ne 0 -a "$1" = "--stdout" ] ; then
  shift
  use_pager=false
fi

query="$@"
suff="$(echo $query | sed 's/ /-/g' | awk '{print tolower($0)}')"
print_as_md() {
  pandoc -f html -t markdown https://based.cooking/$suff | sed '/^:::.*$/d'
}

if [ "$use_pager" = false ] ; then
  print_as_md
  exit 0
fi
print_as_md | ${PAGER:-less}
