#!/bin/sh

_woman_complete() {
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  dashoptions='--list --tags --stdout'

  case "$prev" in
  woman)
    case "$cur" in
    -*)
      COMPREPLY=( $( compgen -W "$dashoptions" -- $cur ) )
      return 0

    ;;
    *)
      local IFS=$'\n'
      names=`woman --list`
      COMPREPLY=( $( grep -i "^$cur" <( echo "$names" ) | sed -e 's/ /\\ /g' ) )
      return 0

    ;;
    esac

  ;;
  --stdout)
    local IFS=$'\n'
    names=`woman --list`
    COMPREPLY=( $( grep -i "^$cur" <( echo "$names" ) | sed -e 's/ /\\ /g' ) )
    return 0

  ;;
  --list)
    tags=`woman --tags`
    COMPREPLY=( $( grep -i "^$cur" <( echo "$tags" ) ) )
    return 0

  ;;
  esac
}

complete -o bashdefault -o default -o nospace -F _woman_complete woman
